# Generated by Django 2.0.6 on 2018-08-16 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deicide', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deicidelist',
            name='Acqusation',
            field=models.CharField(max_length=65),
        ),
    ]
