# Generated by Django 2.0.6 on 2018-08-16 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deicide', '0002_auto_20180816_1655'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeicideListArchive',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Gods_Name', models.CharField(max_length=20)),
                ('Acqusation', models.CharField(max_length=65)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
