# Generated by Django 2.0.6 on 2018-08-16 21:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('deicide', '0003_deicidelistarchive'),
    ]

    operations = [
        migrations.RenameField(
            model_name='deicidelist',
            old_name='Acqusation',
            new_name='Accusation',
        ),
        migrations.RenameField(
            model_name='deicidelistarchive',
            old_name='Acqusation',
            new_name='Accusation',
        ),
    ]
