# Generated by Django 2.0.6 on 2018-08-16 22:22

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('deicide', '0004_auto_20180816_2134'),
    ]

    operations = [
        migrations.AddField(
            model_name='deicidelist',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
